
### 회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "abc3@hongik.ac.kr",
  "nickname": "자몽",
  "password": "12341234",
  "confirmPassword": "12341234",
  "agree": "true"
}

### 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "12341234"
}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQzMjg0ODM5fQ.x2IgY-CWDyq0HUIY2wY90ELmGsvIS3ovP30KvkmKLOg",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQ0NDk0NDA5fQ.6rqhONW9Afh7PtZ0d7p-ZWsy1eqSItNQ_OlKnxlvTsw"
}

### 게시글 조회
GET http://localhost:8090/v1/boards/1/posts/4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NDQ0NzE3NzAsImV4cCI6MTY0NDU1ODE3MH0.fDnacYhw_dd2K_tD15JuMY0PGTfBPpbn_X-4Evv1gNo

### 게시글 전체 조회
GET http://localhost:8090/v1/boards/1/posts

### 게시글 저장
POST http://localhost:8090/v1/boards/1/posts
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc
Content-Type: application/json

{
  "title": "샘플 포스트",
  "tags": ["aa","bb"],
  "content": "샘플 포스트 컨텐츠"
}

### 게시글 수정
PUT http://localhost:8090/v1/boards/1/posts/4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc
Content-Type: application/json

{
  "title": "샘플 포스트1",
  "tags": ["aa1","bb2"],
  "content": "샘플 포스트 컨텐츠2"
}

### 게시글 삭제
DELETE http://localhost:8090/v1/boards/1/posts/4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc


### 댓글 등록
POST http://localhost:8090/v1/posts/4/comments
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc
Content-Type: application/json

{
  "content" : "댓글 테스트1 ."
}

### 댓글 수정
PUT http://localhost:8090/v1/posts/4/comments/5
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0Mzk4MDEyOSwiZXhwIjoxNjQ0MDY2NTI5fQ.vawWyp83-W7jRyB0Jx9JRQRltrRRQqA0MBZ-ui6zUsQ
Content-Type: application/json

{
  "content" : "댓글 테스트1234 ."
}

### 댓글 삭제
DELETE http://localhost:8090/v1/posts/4/comments/8
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMzQGhvbmdpay5hYy5rciIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjQ0NDcwODk2LCJleHAiOjE2NDQ1NTcyOTZ9.MmM12CljlMs_bI06Jm3WS5FHTZ2LLoksTHOrBZ81SBM
Content-Type: application/json

### 게시글 좋아요 요청
POST http://localhost:8090/v1/posts/4/like
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMzQGhvbmdpay5hYy5rciIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjQ0NDcyMDM0LCJleHAiOjE2NDQ1NTg0MzR9.6KQ4IbdFkCPgSRbLG2MPBEMeisLNETb4ISesHvu2h0c


### 메인화면 전체 게시글 조회
GET http://localhost:8090/v1/main?page=0

### 회원 정보 조회
GET http://localhost:8090/v1/users/1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc

### 회원 정보 수정
PUT http://localhost:8090/v1/users/1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc
Content-Type: application/json

{
  "nickname": "테스트2",
  "introduction" : "소개입니다.",
  "personalUrl" : "http://cafe.naver.com",
  "infoByEmail" : true,
  "infoByWeb" : true
}

### 회원 탈퇴
DELETE http://localhost:8090/v1/users/1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOiJST0xFX1VTRVIiLCJuaWNrbmFtZSI6InRlc3QiLCJ1c2VySWQiOjEsInByb2ZpbGVJbWFnZSI6Ik4iLCJpYXQiOjE2NDQ0ODIyOTIsImV4cCI6MTY0NDU2ODY5Mn0.KyJ5jdFJqPDZVpQF-VrVyUDuL-A2Qau_JwAdnie13dc