#회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "nickname": "string",
  "password": "12342134"
}

### 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "string123123"
}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MjY5NjI3MywiZXhwIjoxNjQyNjk5ODczfQ.jGML5KAcgWo4EOAcu7NpBty_8HpFl87OmH2s7fkeHco",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MjY5NjI3MywiZXhwIjoxNjQzOTA1ODczfQ.Q00obCIagjBV9FWrVVTadNb1VrngFkceKvaOkHLaaww"
}


### 회원 정보 조회
GET http://localhost:8090/v1/user/id/1
X-AUTH-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MjY5NDgxMSwiZXhwIjox



