#회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "nickname": "string",
  "password": "12341234",
  "confirmPassword": "12341234",
  "agree": "true"
}

### 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "12341234"
}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQzMjg0ODM5fQ.x2IgY-CWDyq0HUIY2wY90ELmGsvIS3ovP30KvkmKLOg",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQ0NDk0NDA5fQ.6rqhONW9Afh7PtZ0d7p-ZWsy1eqSItNQ_OlKnxlvTsw"
}


### 회원 정보 조회
GET http://localhost:8090/v1/user/id/1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzY5Mjc5NSwiZXhwIjoxNjQzNjk5OTk1fQ.9rmYLZJKHCniSUkLNH-lje_x9i7cn2tyAg09hZKXPlo


### 게시글 저장
POST http://localhost:8090/v1/boards/1/posts
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzcxMzExOSwiZXhwIjoxNjQzNzk5NTE5fQ.lmoI8SylBcTx2n1-YSGqfYnggGnJ9CIAmfzzjzSgxis
Content-Type: application/json

{
  "title": "샘플 포스트",
  "tags": ["aa","bb"],
  "content": "샘플 포스트 컨텐츠"
}

### 게시글 수정
PUT http://localhost:8090/v1/boards/1/posts/4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzcxMzExOSwiZXhwIjoxNjQzNzk5NTE5fQ.lmoI8SylBcTx2n1-YSGqfYnggGnJ9CIAmfzzjzSgxis
Content-Type: application/json

{
  "title": "샘플 포스트1",
  "tags": ["aa1","bb2"],
  "content": "샘플 포스트 컨텐츠2"
}

### 게시글 조회
GET http://localhost:8090/v1/boards/1/posts/4

