### 배너 등록
POST http://{{serverUrl}}/v1/banners
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title" : "배너",
  "nickname" : "관리자",
  "content" : "배너 입니다.",
  "url" : "http://cafe.naver.com",
  "imgUrl" : "{{imageURL}}",
  "tags" : ["자바","자바1"]
}
> {%
client.global.set("bannerId", response.body.data.bannerId);
%}


### 배너 가져오기
GET http://{{serverUrl}}/v1/banners


### 배너 삭제하기
DELETE http://{{serverUrl}}/v1/banners/{{bannerId}}
Authorization: {{Authorization}}
