### 관리자 로그인
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "관리자",
  "password": "1234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}



### 배너 등록
POST http://localhost:8090/v1/banners
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title" : "배너",
  "content" : "배너 입니다.",
  "url" : "http://cafe.naver.com",
  "imgUrl" : "{{imageURL}}",
  "tags" : ["자바","자바1"]
}
> {%
client.global.set("bannerId", response.body.data.bannerId);
%}


### 배너 가져오기
GET http://localhost:8090/v1/banners


### 배너 삭제하기
DELETE http://localhost:8090/v1/banners/{{bannerId}}
Authorization: {{Authorization}}
