
### 이미지 업로드 테스트
POST http://{{serverUrl}}/v1/file/upload
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ScreenCapture.png"
Content-Type: image/png

< C:\Users\busan\ScreenCapture.png
--WebAppBoundary--

> {%
client.global.set("imageURL", response.body.data.imageURL.substr(response.body.data.imageURL.indexOf("d/") + 2,response.body.data.imageURL.indexOf('.')));
client.log("생성된 URL " + client.global.get("imageURL"));
%}


