
### 회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "busan-sy@naver.com",
  "nickname": "자몽",
  "pathId" : "test1",
  "password": "12341234",
  "confirmPassword": "12341234",
  "agree": "true"
}

### 관리자 로그인
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "관리자",
  "password": "1234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 일반 유저 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "12341234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NDU1MjkzMTQsImV4cCI6MTY0NTYxNTcxNH0.QUEboBR9HCI4ff0gfV6OhhFxlikhabmdgBHOcKlJb54",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NDU1MjkzMTQsImV4cCI6MTY1ODA1NzMxNH0.Q8jMcuTaPbuFyCSp1SdqyOu8Zx3sUYFUjph_W8ATa0o"
}

### 이메일 인증
GET http://localhost:8090/v1/email-token?email={{email}}&token={{token}}

### 이메일 인증 재전송
POST http://localhost:8090/v1/email-token
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpYXQiOjE2NDU1MzE1MTMsImV4cCI6MTY0NTYxNzkxM30.OdwRpRbh9yS_9YigDygv1YEsfX_XaT0dLSBsqvgqWKw"


### 구글 로그인
http://localhost:8090/oauth2/authorization/google