
### 회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "busan-sy@naver.com",
  "nickname": "테스트",
  "pathId" : "test1",
  "password": "12341234",
  "confirmPassword": "12341234",
  "agree": "true"
}

### 관리자 로그인
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "관리자",
  "password": "1234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 일반 유저 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "12341234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQzMjg0ODM5fQ.x2IgY-CWDyq0HUIY2wY90ELmGsvIS3ovP30KvkmKLOg",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAaG9uZ2lrLmFjLmtyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTY0MzI4NDgwOSwiZXhwIjoxNjQ0NDk0NDA5fQ.6rqhONW9Afh7PtZ0d7p-ZWsy1eqSItNQ_OlKnxlvTsw"
}

