
### 회원가입  정상 요청
POST http://localhost:8090/v1/signup
Content-Type: application/json

{
  "email": "busan-sy@naver.com",
  "nickname": "자몽",
  "pathId" : "test1",
  "password": "12341234",
  "confirmPassword": "12341234",
  "agree": "true"
}

### 관리자 로그인
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "관리자",
  "password": "1234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 일반 유저 로그인 정상 요청
POST http://localhost:8090/v1/login
Content-Type: application/json

{
  "email": "abc@hongik.ac.kr",
  "password": "12341234"
}
> {%
client.global.set("Authorization", response.body.data.accessToken);
client.log("생성된 보안키" + client.global.get("Authorization"));
%}

### 토큰 재발급 정상 요청
POST http://localhost:8090/v1/reissue
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLqtIDrpqzsnpAiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsInVzZXJJZCI6MiwicHJvZmlsZUltYWdlIjoiTiIsImlhdCI6MTY0NTAxNDMyOSwiZXhwIjoxNjQ1MTAwNzI5fQ.V7yKuIK0A5TCR4Uf3mdKDnKwYxVpLNCM7DNccnvQHzk",
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLqtIDrpqzsnpAiLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsInVzZXJJZCI6MiwicHJvZmlsZUltYWdlIjoiTiIsImlhdCI6MTY0NTAxNDMyOSwiZXhwIjoxNjU3NTQyMzI5fQ.WIlVYYNONzpAs2_SMxw0kIo-m24iLOgZsh0ooucbPQo"
}

### 이메일 인증
GET http://localhost:8090/v1/email-token?email={{email}}&token={{token}}

### 이메일 인증 재전송
POST http://localhost:8090/v1/email-token
Authorization: {{Authorization}}