### 회원 정보 조회
GET http://localhost:8090/v1/users/2
Authorization: {{Authorization}}

### 회원 정보 수정
PUT http://localhost:8090/v1/users/2
Authorization: {{Authorization}}
Content-Type: application/json

{
  "nickname": "테스트2",
  "introduction" : "소개입니다.",
  "personalUrl" : "http://cafe.naver.com",
  "infoByEmail" : true,
  "infoByWeb" : true
}

### 회원 탈퇴
DELETE http://localhost:8090/v1/users/2
Authorization: {{Authorization}}

> {%
client.log("현재 보안키" + client.global.get("Authorization"));
%}