### 회원 정보 조회
GET http://localhost:8090/v1/users/1
Authorization: {{Authorization}}

### 회원 정보 수정
PUT http://localhost:8090/v1/users/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "nickname": "테스트2",
  "introduction" : "소개입니다.",
  "personalUrl" : "http://cafe.naver.com",
  "infoByEmail" : true,
  "infoByWeb" : true
}

### 회원 탈퇴
DELETE http://localhost:8090/v1/users/2
Authorization: {{Authorization}}

### 회원 비밀번호 변경
PUT http://localhost:8090/v1/users/1/updatePassword
Authorization: {{Authorization}}
Content-Type: application/json

{
  "password" : "12341234",
  "confirmPassword" : "12341234"

}


### 모든 유저 조회 ( 개인게시판 유저 정보 조회 )
GET http://{{serverUrl}}/v1/users
